C  DEC/CMS REPLACEMENT HISTORY, Element HO_DEV.I
C  *3     1-MAR-1990 16:40:36 WALTERS "(SPR 0) Fix SUN compiler warnings and errors"
C  *2    12-AUG-1989 12:02:17 GILLESPIE "(SPR 2) Comments were a bit off"
C  *1    30-JUN-1989 15:17:45 GILLESPIE ""
C  DEC/CMS REPLACEMENT HISTORY, Element HO_DEV.I

      INTEGER*4 HO_USER_TERMINAL, HO_DMA_DEVICE, HO_ASYNC_LINE
      PARAMETER ( HO_USER_TERMINAL = 0 )
      PARAMETER ( HO_DMA_DEVICE = 1 )
      PARAMETER ( HO_ASYNC_LINE = 3 )
