C  DEC/CMS REPLACEMENT HISTORY, Element MO_STRUCT.I
C  *3     3-NOV-1989 10:51:05 GILLESPIE "(SPR 1) Change in nomenclature for n-List stuff"
C  *2    19-SEP-1989 12:35:32 GORDON "(SPR 100) latest Gulf version"
C  *1    30-JUN-1989 15:17:58 GILLESPIE ""
C  DEC/CMS REPLACEMENT HISTORY, Element MO_STRUCT.I
   
C
C SHUTDOWN COMMAND FROM C TO F77
C
      INTEGER*4 MO_F77_SHUTDOWN
      PARAMETER (MO_F77_SHUTDOWN = -999)
C
C MODEL STRUCTURE AS PASSED FROM MODEL DIGITIZING C PROGRAM.
C SIZE IS IN 32 BIT WORDS!!!! NOT BYTES!!!!!
C
      PARAMETER (MO_SIZE = 48)
      INTEGER*4 MO_STRUCT(MO_SIZE)
C
C PUT IT IN A COMMON BLOCK
C
      COMMON/MO_STRUCT_COMMON/MO_STRUCT
C
C EACH FIELD IS GIVEN A FORTRAN VARIABLE NAME AND EQUIVALENCED TO IT
C PLACE IN THE STRUCTURE.  CHARACTER FIELDS ALSO HAVE A VARIABLE CALLED
C E_FIELD_NAME SO THE LOC CAN BE PASSED AROUND.
C
C LISTHEADS ARE DECLARED AS CHARACTER JUST TO SHOW THEIR
C LENGTHS. ONLY THE E_ VARIABLES WILL BE USED.
C
C DEFINE FIELDS
C
      REAL*8 LOG_START
      EQUIVALENCE(MO_STRUCT(1),LOG_START)
C
      CHARACTER*12 MO_UOM
      EQUIVALENCE ( MO_STRUCT(3), MO_UOM, E_MO_UOM)
C
      CHARACTER*40 LISTHEAD_UWIS
      EQUIVALENCE(MO_STRUCT(6),LISTHEAD_UWIS,E_LISTHEAD_UWIS)
C
      CHARACTER*132 MO_NAME
      EQUIVALENCE(MO_STRUCT(14),MO_NAME,E_MO_NAME)

CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C   HERE WE DEFINE THE FORTRAN EQUIVILANCES FOR THE C STRUCTURE RETURNED
C    FROM LLFIRST AND LLNEXT LINK LIST CALLS.  THE CURRENT LENGTH OF 
C    THE STRUCTURE IS 32 BYTES (FEB. 1988).  IT MUST BE REDEFINED IF 
C    THE C STRUCTURE CHANGES (IE UWI LENGTH CHANGES, ETC.)
C
C             BYTES  1 - 24:   UWI
C             BYTES  25 - 32:  XPOSITION (OF WELL)
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      REAL*8 UWIX(4),XPOSITION
      CHARACTER*20 UWI
      EQUIVALENCE(UWI,UWIX(1),E_UWI),(XPOSITION,UWIX(4))



